### ISSUE TITLE
down完这个项目后，获取info信息报错

### ISSUE THREAD

**Issue by youtianhong** [zhengfc/redis-cluster-monitor#3]
Hi zheng,

非常感谢你提供了java版的直接获取redis服务器的信息demo.
当我down我在本地跑的时候，cluster connection已经连接上了，但当我调用
@RequestMapping(value = "/cluster/info", method = RequestMethod.GET) 获取info信息的时候，

报如下错误，

	org.springframework.data.redis.ClusterStateFailureException: Could not retrieve cluster information. CLUSTER NODES returned with error.
	- 10.132.97.102:7005 failed: Hostname must not be empty or null.
	- xx.xx.xx.102:7003 failed: Hostname must not be empty or null.
	- xx.xx.xx.102:7004 failed: Hostname must not be empty or null.
	- xx.xx.xx.102:7001 failed: Hostname must not be empty or null.
	- xx.xx.xx.102:7002 failed: Hostname must not be empty or null.
	- xx.xx.xx.102:7000 failed: Hostname must not be empty or null.

我在redis.properties中已经替换了redis IP和端口
spring.redis.cluster.nodes=xx.xx.xx.102:7000,xx.xx.xx.102:7001,xx.xx.xx.102:7002,xx.xx.xx.102:7003,xx.xx.xx.102:7004,xx.xx.xx.102:7005

测试环境同一台服务器集群如下：
root     10452  0.0  0.2 115856 10620 ?        Ssl  Sep26   1:44 /opt/redis-3.0.0-rc1/src/redis-server *:7000 [cluster]               
testuser 21834  0.0  0.0  61192   728 pts/0    R+   10:55   0:00 grep redis
root     30436  0.0  0.2 103568 12072 ?        Ssl  Jun08   5:03 /opt/redis-3.0.0-rc1/src/redis-server *:7001 [cluster]               
root     30446  0.0  0.3 107664 12176 ?        Ssl  Jun08   4:25 /opt/redis-3.0.0-rc1/src/redis-server *:7002 [cluster]               
root     30451  0.0  0.3 119952 12320 ?        Ssl  Jun08   5:32 /opt/redis-3.0.0-rc1/src/redis-server *:7003 [cluster]               
root     30458  0.0  0.2 103568 10744 ?        Ssl  Jun08   3:38 /opt/redis-3.0.0-rc1/src/redis-server *:7004 [cluster]               
root     30465  0.0  0.2 103568 10756 ?        Ssl  Jun08   3:26 /opt/redis-3.0.0-rc1/src/redis-server *:7005 [cluster

请帮忙看看什么原因造成的?

非常感谢！

**Comment by zhengfc** [comment]
* 该issue提交者反应，集群增删节点未完全清理干净导致，见以下链接
https://my.oschina.net/hollowj/blog/792063
